[package]
name = "game-system-design-practices"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "simple_health_system",
    "simple_health_system_v2"
]

[workspace.dependencies]
bevy = { version = "0.15.1", features = [  "default", "wayland", ] }

